### ISSUE TITLE
TODO - upload_to_algolia.php

### ISSUE THREAD

**Issue by adamevers** [nu-foundation/nu_community_api#1]
- [x] need to add region short code - California = CA
- [x] need to add country FULL name - US = United States
- [ ] need to update region abbreviations for Canada, Australia and United Kingdom
